# Generated by Django 4.0.5 on 2022-06-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INITIAL CONTACT', 'Initial Contact'), ('PHONE SCREEN', 'Phone Screen'), ('INTERVIEW', 'Interview'), ('IN CONSIDERATION', 'In Consideration'), ('HIRED', 'Hired'), ('DECLINED', 'Declined'), ('WITHDREW', 'Withdrew')], default='INITIAL CONTACT', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.CharField(max_length=100)),
                ('linkedIn', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
