# Generated by Django 4.0.5 on 2022-06-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='linkedIn',
            new_name='linkedin',
        ),
    ]
